name: JET10
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/oyunlar/Breaker/
    - assets/oyunlar/ChopChop/
    - assets/oyunlar/Dart/
    - assets/oyunlar/Dash/
    - assets/oyunlar/Helix/
    - assets/oyunlar/Roller/
    - assets/oyunlar/Snake/
    - assets/oyunlar/Sort/
    - assets/oyunlar/ColorBall/
    - assets/oyunlar/Tiles/
    - assets/oyunlar/Tower/
    - assets/oyunlar/StickMaster/
    - assets/oyunlar/ZigZag/
    - assets/oyunlar/shared/