// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'YOUR_FIREBASE_API_KEY'),
    appId: '1:743245476829:web:ba8a4af6e8c696e9793c34',
    messagingSenderId: '743245476829',
    projectId: 'kaeru-jet10-app',
    authDomain: 'kaeru-jet10-app.firebaseapp.com',
    storageBucket: 'kaeru-jet10-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'YOUR_FIREBASE_API_KEY'),
    appId: '1:743245476829:android:b7b496746c4b0f7b793c34',
    messagingSenderId: '743245476829',
    projectId: 'kaeru-jet10-app',
    storageBucket: 'kaeru-jet10-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'YOUR_FIREBASE_API_KEY'),
    appId: '1:743245476829:ios:afca57e244fd5961793c34',
    messagingSenderId: '743245476829',
    projectId: 'kaeru-jet10-app',
    storageBucket: 'kaeru-jet10-app.firebasestorage.app',
    iosBundleId: 'com.kaeru.jet10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'YOUR_FIREBASE_API_KEY'),
    appId: '1:743245476829:ios:afca57e244fd5961793c34',
    messagingSenderId: '743245476829',
    projectId: 'kaeru-jet10-app',
    storageBucket: 'kaeru-jet10-app.firebasestorage.app',
    iosBundleId: 'com.kaeru.jet10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY', defaultValue: 'YOUR_FIREBASE_API_KEY'),
    appId: '1:743245476829:web:5df7f5f05e23478a793c34',
    messagingSenderId: '743245476829',
    projectId: 'kaeru-jet10-app',
    authDomain: 'kaeru-jet10-app.firebaseapp.com',
    storageBucket: 'kaeru-jet10-app.firebasestorage.app',
  );
}
