// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRCqYbe4DNPvmuwGydbd12fEhKMpBacE',
    appId: '1:979530283005:web:af81c962be5bc42dce8b94',
    messagingSenderId: '979530283005',
    projectId: 'jet10-app',
    authDomain: 'jet10-app.firebaseapp.com',
    storageBucket: 'jet10-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAbe5BzOTGKBhjvHQcJ5gyVI5fX8I0opU',
    appId: '1:979530283005:android:2cf000600e95e18ace8b94',
    messagingSenderId: '979530283005',
    projectId: 'jet10-app',
    storageBucket: 'jet10-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnzcIx179Ti5DDcToy4SNzuiqE_GaGRMY',
    appId: '1:979530283005:ios:6041dd2df2b2cfdece8b94',
    messagingSenderId: '979530283005',
    projectId: 'jet10-app',
    storageBucket: 'jet10-app.firebasestorage.app',
    iosBundleId: 'com.example.jet10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnzcIx179Ti5DDcToy4SNzuiqE_GaGRMY',
    appId: '1:979530283005:ios:6041dd2df2b2cfdece8b94',
    messagingSenderId: '979530283005',
    projectId: 'jet10-app',
    storageBucket: 'jet10-app.firebasestorage.app',
    iosBundleId: 'com.example.jet10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASRCqYbe4DNPvmuwGydbd12fEhKMpBacE',
    appId: '1:979530283005:web:e9909d8e9a094a34ce8b94',
    messagingSenderId: '979530283005',
    projectId: 'jet10-app',
    authDomain: 'jet10-app.firebaseapp.com',
    storageBucket: 'jet10-app.firebasestorage.app',
  );
}
